version: '2'
services:
  api:
    build: .
    restart: always
  lb:
    image: 'dockercloud/haproxy:1.2.1'
    restart: always
    links:
     - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8080:80'  